### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by smatsumori** [imai-laboratory/hackathon-2017-sample#6]
ここに思いつく限りのcontributionを書いてください。

**Comment by Toxy** [comment]
* Depth, Rotation, Movementからプレイヤーの絶対座標を推定するPosition Trackモジュールの実装
* Position TrackモジュールはPlaceCellの教師データとした
* 複数GPUの使用オプション
* ProductNameの変更によるPlayerPrefsの競合解消（複数のUnityでAgentを同時起動できるようにした）
